language: python
python:
  - "2.7"
before_script:
  - psql -c 'create database oneanddone;' -U postgres
  - cp oneanddone/settings/local.py-travis oneanddone/settings/local.py
install:
  - pip install -r requirements.txt
env:
  - DJANGO_DEBUG=False DJANGO_SECRET_KEY='FOO' DJANGO_HMAC_KEY='FOO' ALLOWED_HOSTS=localhost, DATABASE_URL=postgres://postgres:@localhost/oneanddone
script: python manage.py test
