language: python
python:
  - "2.7"
before_script:
  - mysql -e 'create database oneanddone character set utf8;'
  - cp oneanddone/settings/local.py-travis oneanddone/settings/local.py
install:
  - pip install -r requirements/requirements.txt
env:
  - DEBUG=False SECRET_KEY='FOO' ALLOWED_HOSTS=localhost, DATABASE_URL=mysql://root:@localhost:3306/oneanddone
script: python manage.py test
